### ISSUE TITLE
Logo & branding

### ISSUE THREAD

**Issue by markets** [ralixjs/ralix#16]
We need a logo to make some branding and online presence ✨ 

Our idea is a simplistic/minimal logo according to the project "values". Our "tagline" is: "The bare necessities", so we thought a "geometric" bear fits really well as our logo :bear:

**Comment by maguri** [comment]
this is a nice tool to create some cool logo: https://www.namecheap.com/logo-maker/app/

**Comment by markets** [comment]
![cover](https://user-images.githubusercontent.com/576701/70287008-b32c9780-17cd-11ea-9ba7-6556223bfc8a.png)

**Comment by maguri** [comment]
I vote **yes** for this one!

**Comment by markets** [comment]
@maguri I pushed a new version without gradient, to make it simpler, and different versions (cover, default, profile, svg and monochrome black): https://github.com/ralixjs/ralix/tree/master/logos
