### ISSUE TITLE
Uncaught ReferenceError

### ISSUE THREAD

**Issue by maguri** [ralixjs/ralix#3]
In some cases, when I try to use core methods as (find, findAll) into the controller constructor, it raises this error:

```js
Uncaught ReferenceError: find is not defined
```

**[PROBLEM]** It seems that when Controller is created, *Ralix* has not added the core methods into window object yet.

**Comment by markets** [comment]
@maguri agree it would be better to use the ***core*** methods in the same way, always. I'll take a look to this.

**Comment by markets** [comment]
@maguri closed by #8 => new approach without RalixCtrl 🚀 

I'm goint to prepare a new release and push it to `npm`.
