### ISSUE TITLE
Add a new helper method to be able to remove events listeners

### ISSUE THREAD

**Issue by jfelip937** [ralixjs/ralix#51]
To be able to remove all listeners of a type/types given an element/array/query selector. 

As we already have the `on` method it will be consistent to have a method to remove the listeners.

**PROPOSED SOLUTION**

To remove a specific eventListener:

```
unbind(elements, events, function)
```

To remove all eventListeners:

```
unbind(elements, events)
```
Arguments:

- elements: Element / Array of Elements / Query selector
- events: String with the type of events to remove
- function: eventListener to be removed. If not added all eventListeners of the given types will be removed.

**Comment by markets** [comment]
hey @jfelip937 👋🏼 I'm not sure about the need to add this helper, maybe we can close it for now and re-open in case we need it on any app?

Another option is to implement a simpler `off` helper, which is basically like `on` but with `removeEventListener`... but removing event listeners seems a much less common operation, perhaps we can just close this proposal for now.
