### ISSUE TITLE
New back() helper

### ISSUE THREAD

**Issue by markets** [ralixjs/ralix#71]
Provide `back()` helper (under [Navigation](https://github.com/ralixjs/ralix/blob/master/docs/HELPERS_API.md#navigation)), but with a fallback url: 

```js
back(fallbackUrl = null) {
  ...
}
```

Some times, I'd like to use something:

```html
<a href="#" onclick="back('/home')">Back</a>
```

In case someone visits the page with that button, without a referrer, at least to easily provide a fallback url. It seems useful to me.

What do you think @jfelip937 @araluce @AlexLarra @franpb14?

**Comment by franpb14** [comment]
It also seems simple to implement. I think it could be good.

**Comment by araluce** [comment]
Yeah, it makes sense this to have a place in Ralix
