### ISSUE TITLE
Improve toggleClass to accept a boolean value

### ISSUE THREAD

**Issue by jfelip937** [ralixjs/ralix#78]
**PROBLEM**

We might want to add or remove a class depending on a boolean and then we end with an example like this:
```js
if(value) {
  addClass(".container", "hide")
} else {
  removeClass(".container", "hide")
}
```

**PROPOSED SOLUTION**

Use a state optional value to know if the class has to be removed or added.
```js
toggleClass(".container", "hide", value)
```

**Notes**

- This is already supported by classList.toggle() so it should only be to forward the boolean. https://developer.mozilla.org/en-US/docs/Web/API/DOMTokenList/toggle#setting_the_force_parameter

**Comment by markets** [comment]
Like it! Cool small feature 👌
