### ISSUE TITLE
For the `ajax` calls return the Response object

### ISSUE THREAD

**Issue by jfelip937** [ralixjs/ralix#83]
**Problem**

Right now we don't have any information as how the request went (status code) as we are only returning the parsed body of the response.

**Proposed solution**

Return the whole Response object.

**Notes**
- This would be a breaking change.
- We will have to parse the response but this will give as more flexibility.

**Comment by markets** [comment]
I get your point and I agree that sometimes will be better to return the Response object. To avoid a breaking change, maybe we can keep the current behaviour and introduce a new flag or a custom response handler to return the whole object?

**Comment by jfelip937** [comment]
@markets yes we could have an option like `parseResponse`. I would say that by default is true so it's not a breaking changes but we can check the response in some cases

**Comment by markets** [comment]
@jfelip937 I'm still not 100% convinced on adding more stuff in the `ajax` helper (code + docs), which is one of the most complex ones we have. You can still use native `fetch` for those cases.
